/*
 * jstoryFrame.java
 *
 * Created on December 5, 2006, 11:27 AM
 */

/**
 *
 * @author  VisokayA
 */

import java.io.*;
import java.net.*;
import java.util.*;
import java.lang.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.event.*;
import javax.swing.JComponent;

public class jstoryFrame extends javax.swing.JFrame {
    jstoryPanel storyPanel =null;
    static HeadlineInfo hInfo =null;
    static int irow =0;
    
    /** Creates new form jstoryFrame */
    public jstoryFrame(HeadlineInfo hi, int row) {
        hInfo = hi;
        irow = row;
        initComponents();
        myinitcomponents();
        pack();
        setSize(750,700);
        jmainFrame.jstoryframe = this;
    }
    
     public void myinitcomponents(){
        final JFrame frame = this; 
        this.setTitle(hInfo.FE+hInfo.Timestamp);
        storyPanel = new jstoryPanel(this);                   
        getContentPane().add(storyPanel);
        storyPanel.initStoryInfo(hInfo,irow);
    }
    
   public jstoryPanel getStorydetailsPanel(){
        return storyPanel;
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFont(new java.awt.Font("Magneto", 0, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
